apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend
  namespace: openshift-gitops
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          frontend: gui
  template:
    metadata:
      name: 'frontend-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/burrsutter/polycloud'
        targetRevision: main
        path: 'argocd-frontend/base'
      destination:
        server: '{{server}}'
        namespace: hybrid
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
      - group: ""
        kind: Secret
        jsonPointers:
        - /data