apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/burrsutter/polycloud.git
    targetRevision: HEAD
    path: argocd-frontend/base
  destination:
    server: https://kubernetes.default.svc
    namespace: hybrid